service: birthday-bot-node-to-image
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    AWS_S3_ACCESS_KEY_ID: ${env:AWS_S3_ACCESS_KEY_ID}
    AWS_S3_SECRET_ACCESS_KEY: ${env:AWS_S3_SECRET_ACCESS_KEY}
	
package:
  patterns:
    - '!node_modules/puppeteer/**'

functions:
  function1:
    handler: app.handler
   
